version: '3'
services:
  ui:
    image: dashboard.test.ui:latest
    build:
      context: ./ui
      dockerfile: Dockerfile
    volumes:
      - ./ui:/ui
      - /ui/node_modules
    ports:
      - "3000:3000"
    command: yarn start
  server:
    image: dashboard.test.server:latest
    build:
      context: ./server
      dockerfile: Dockerfile
    volumes:
      - ./server:/server
      - /server/node_modules
    ports:
      - "8080:8080"
    command: yarn start
